// Generated by CoffeeScript 1.3.3
(function() {
  var i, name, path, tank, tank_i, tank_j, tanks, tourney_dir, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2, _ref3;

  _ref = process.argv.slice(2), name = _ref[0], path = _ref[1], tourney_dir = _ref[2];

  _ref1 = readirSync(tourney_dir);
  for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
    tank = _ref1[_i];
    tanks = require(tank);
  }

  _ref2 = tanks.slice(0, (tanks.length - 2) + 1 || 9e9);
  for (i = _j = 0, _len1 = _ref2.length; _j < _len1; i = ++_j) {
    tank_i = _ref2[i];
    _ref3 = tanks.slice(i + 1, (tanks.length - 1) + 1 || 9e9);
    for (_k = 0, _len2 = _ref3.length; _k < _len2; _k++) {
      tank_j = _ref3[_k];
      run_match(tank_i, tank_j);
    }
  }

  ({
    run_match: function(ti, tj) {
      var game, _l, _results;
      _results = [];
      for (i = _l = 1; _l <= 5; i = ++_l) {
        game = new Game("rofl" + i);
        game.register_tank(ti.name, ti.step, ti.init);
        game.register_tank(tj.name, tj.step, tj.init);
        game.init();
        _results.push((function() {
          var _results1;
          _results1 = [];
          while (!game.is_complete()) {
            _results1.push(game.step());
          }
          return _results1;
        })());
      }
      return _results;
    }
  });

}).call(this);
